[package]
name = "cleanup-bot"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1"
indoc = "2.0.7"
poise = "0.6.1"
serde = { version = "1.0.228", features = ["derive"] }
serenity = "0.12.5"
shared = { version = "0.1.0", path = "../shared" }
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread", "time", "sync", "fs", "process"] }
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
reqwest = { version = "0.12", features = ["stream", "json"] }
toml = "0.9.11"
thiserror = "2.0"
tracing = "0.1.44"
serde_json = "1.0.149"
